AWSTemplateFormatVersion: '2010-09-09'
Description: Amira storydb editor
Resources:
  StorydbDynamo:
    Properties:
      AttributeDefinitions:
      - AttributeName: name
        AttributeType: S
      KeySchema:
      - AttributeName: name
        KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      TableName: magic-training
    Type: AWS::DynamoDB::Table
