AWSTemplateFormatVersion: '2010-09-09'
Description: Amira storydb editor
Resources:
    StorydbDynamo:
        Type: AWS::DynamoDB::Table
        Properties:
            TableName: magic-training
            ProvisionedThroughput:
                ReadCapacityUnits: 1
                WriteCapacityUnits: 1
            AttributeDefinitions:
                -   AttributeName: name
                    AttributeType: S
            KeySchema:
                -   AttributeName: name
                    KeyType: HASH